### ISSUE TITLE
System environment variables

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#109]
These environment variables will mount to every container to enable integrations from within the containers:

- `ONEPANEL_API_URL` - Format: `<http-scheme>://<host>[:<apiHTTPPort>]/[apiPath]`
- `PROVIDER_TYPE` - `local` or `cloud`

**Comment by aleksandrmelnikov** [comment]
@rushtehrani 
Right now, the ConfigMap value is escaped like so.
```
	"onepanelApiUrl": "http\\:\\/\\/alexcluster\\.onepanel\\.io\\:32000",
```
Should the value not be escaped?

**Comment by rushtehrani** [comment]
> @rushtehrani
> Right now, the ConfigMap value is escaped like so.
> 
> ```
> 	"onepanelApiUrl": "http\\:\\/\\/alexcluster\\.onepanel\\.io\\:32000",
> ```
> 
> Should the value not be escaped?

Does it need to be? Do we use this anywhere else? If not, then it's best not to escape it as that's just a string.

**Comment by aleksandrmelnikov** [comment]
Gotcha, will do

**Comment by aleksandrmelnikov** [comment]
@rushtehrani 
Spot check.
This is what the env vars look like:
```
    - name: main
      image: 'docker/whalesay:latest'
      command:
        - cowsay
      args:
        - hello world
      env:
        - name: onepanelApiUrl
          value: 'http\:\/\/alexcluster\.onepanel\.io\:32000'
        - name: providerType
          value: local
```
I'm still working on the escaping.
