### ISSUE TITLE
Add `type` to `arguments.parameters` in Argo Workflows

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#110]
Support HTML input and select types for Argo Workflow YAMLs. Example:

```
arguments:
    parameters:
    - name: name
       value: 'workspace name'
       type: input.text
    - name: description
       value: 'workspace description'
       type: textarea.textarea
    - name: machine-type
       value: p3.2xlarge
       type: select.select
       options:
          - name: 'V100 GPU'
             value:  p3.xlarge
    - name: image-type
       value: pytorch-1.4
       type: input.radio
       options:
          -  pytorch-1.4
          -  tensorflow-2.0
```
We could use [Gantry Field Types](http://docs.gantry.org/gantry5/advanced/particle-yaml-field-types) as reference but only need to support basic HTML fields listed above for now.

On the API side, the field types and YAML structure need to be validated, but removed before they are passed into [Argo validation](https://github.com/onepanelio/core/blob/07f4e84c85844909b887eba7441ac914675f6ff7/pkg/workflow_execution.go#L223)
