### ISSUE TITLE
Workspaces

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#148]
### Creating a new template
When creating a new template:
- Admin clicks "New template"
- Admin is presented with a generated base specifications with comments
- There will be three separate specifications text areas, one for StatefulSets, one for Service and one for VirtualService
- Additional specification area for defining a DAG for after creation.
- Admin can make changes to these and save the template.

## Technical implementation
Workspace templates consist of the following Kubernetes and Istio components:

- StatefulSet: define the containers and volumes in the Workspace. Containers will be running on certain ports that will need to be exposed.
- Service: internally expose the ports that the containers in StatefulSet are running on as services.
- VirtualService: Map routes to the services above, exposing them externally.

These components are deployed into the cluster using [DAG Workflows and Resource Templates]().

We can create these workflows using [this method](https://github.com/onepanelio/core/blob/master/pkg/workflow_execution.go#L268). However before passing `WorkflowExecution` we need to:

1. Generate the following for the base template:
    - machine-type: this parameter is added automatically, is required and its options are grabbed from `onepanel` configmap.
    - startup-script: this parameter is added automatically, is optional, the value is used in `lifeCycle.postStart` field.
2. Before sending the generated workflow to the above method, validate the `StatefulSet`, `VirtualService` and `Service` and any additional DAG. 
3. If `StatefulSet`, add environment variables from `onepanel-env`.
4. Compose the resources above, and additional DAG into one Workflow. Inject the action, if it's a `delete` action, add a Workflow node for deleting PVCs by iterating through all the available volumes.
5. In the method noted above, get `ONEPANEL_HOST` as defined in #149. 

### Workspace Workflow parts
Note: This workflow needs to be updated to only succeed if resource creation is successful. Another API needs to be added to check health of running StatefulSet

```yaml
arguments:
  parameters:
  ### Begin "Parameters" template
  ### End "Parameters" template
  # Auto-injected parameters
  - name: name
    value: base
    type: input.text
    required: true
  - name: startup-script
    type: textarea.textarea
    value: ''
  - name: machine-type
    type: select.select
    # Generated from `onepanel.onepanel` configMap where `default: true`
    value: Standard_D4s_v3
    # Generated from `onepanel.onepanel` configMap
    options:
    - name: Standard_D4s_v3
      value: Standard_D4s_v3
    required: true
  # Generated based on volumeClaimTemplates names
  - name: <volumeClaimTemplate.metadata.name>-volume-size
    value: 5
    type: input.number
entrypoint: instance-tmpl
templates:
- name: instance-tmpl
  dag:
      tasks:
      - name: service
        template: instance-service-tmpl
      - name: virtual-service
        dependencies: [service]
        template: instance-virtual-service-tmpl
      - name: statefulset
        dependencies: [virtual-service]
        template: instance-statefulset-tmpl
      - name: pvc
        template: instance-pvc-tmpl
        dependencies: [statefulset]
        arguments:
        parameters:
        - name: pvc-name
          value: "{{item}}"
        # List of pvc names to delete
        # Generated based on volumeClaimTemplates names
        withItems:
        - data
        - db
        # Auto-injected based on CreateWorkspace or UpdateWorkspace actions
        when: "{{workflow.parameters.action}} == delete"
- name: instance-service-tmpl
  resource:
    # Auto-injected based on CreateWorkspace or UpdateWorkspace actions
    action: "{{workflow.parameters.action}}"
    manifest: |
      apiVersion: v1
      kind: Service
      metadata:
        # Auto-injected
        name: <<workflow.parameters.name>>
      spec:
        ports:
        ### Begin "Ports" template
        - name: main
          port: 80
          protocol: TCP
          targetPort: 80
        ### End "Ports" template
        # Auto-injected
        selector:
          app: {{workflow.parameters.name}}
        type: ClusterIP
- name: instance-virtual-service-tmpl
  resource:
    # Auto-injected based on CreateWorkspace or UpdateWorkspace actions
    action: "{{workflow.parameters.action}}"
    manifest: |
      apiVersion: networking.istio.io/v1alpha3
      kind: VirtualService
      metadata:
        # Auto-injected
        name: {{workflow.parameters.name}}
      spec:
        # Auto-injected from `onepanel.onepanel` configMap on Workspace creation
        hosts:
        - {{workflow.parameters.name}}-{{workflow.namespace}}<<.workflow.parameters.host>>
        gateways:
        - istio-system/ingressgateway
        http:
        ### Begin "Routes" template
        - match:
          - uri:
              prefix: /
          route:
          - destination:
              port:
                number: 80
              # Auto-injected
              host: {{workflow.parameters.name}}
        ### End "Routes" template
- name: instance-statefulset-tmpl
  resource:
    # Auto-injected based on CreateWorkspace or UpdateWorkspace actions
    action: "{{workflow.parameters.action}}"
    # Auto-injected except when action is "delete"
    successCondition: status.readyReplicas > 0
    manifest: |
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        # Auto-injected
        name: {{workflow.parameters.name}}
      spec:
        replicas: 1
        # Auto-injected
        serviceName: {{workflow.parameters.name}}
        selector:
          matchLabels:
            # Auto-injected
            app: {{workflow.parameters.name}}
        template:
          metadata:
            labels:
              # Auto-injected
              app: {{workflow.parameters.name}}
          spec:
            nodeSelector:
              # Auto-injected from `onepanel.onepanel` configMap on Workspace creation
              <<beta.kubernetes.io/instance-type>>: {{workflow.parameters.machine-type}}
            containers:
            ### Begin "Containers" template
            - name: main
              image: nginxdemos/hello
              # Example startup script
              lifecycle:
                postStart:
                  exec:
                    command: ["/bin/sh", "-c", "{{workflow.parameters.startup-script}}"]
              ports:
              - containerPort: 80
                name: http
              volumeMounts:
                - name: data
                  mountPath: /data
            ### End "Containers" template
        volumeClaimTemplates:
        ### Begin "VolumeClaims" template
        - metadata:
            name: data
          spec:
            # Auto-injected if not defined
            accessModes: ["ReadWriteOnce"]
            # Auto-injected if not defined
            storageClassName: default
            # Auto-injected
            resources:
              requests:
                storage: {{workflow.parameters.data-volume-size}}Mi
        - metadata:
            name: db
          spec:
            # Auto-injected if not defined
            accessModes: ["ReadWriteOnce"]
            # Auto-injected if not defined
            storageClassName: default
            # Auto-injected
            resources:
              requests:
                storage: {{workflow.parameters.db-volume-size}}Mi
        ### End "VolumeClaims" template
- name: instance-pvc-tmpl
  inputs:
    parameters:
    - name: pvc-name
  resource:
    action: delete
    manifest: |
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        # Auto-injected
        name: {{inputs.parameters.pvc-name}}-{{workflow.parameters.name}}-0
```

Note: Workspace names need to be validated with this regex `'[a-z]([-a-z0-9]*[a-z0-9])?'`
