### ISSUE TITLE
Node pool key and machine-type values

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#152]
Node pool key/values are used for `nodeSelector` and autoscaling.

The user will add these in `params.yaml` as follows:

```
application:
  nodePool:
    label: <node-pool-label>
    options:
      - name: <name-1>
        value: <value-1>
      - name: <name-2>
        value: <value-2>
        default: true
```

## Technical implementation
These values will be save in `onepanel` config in `onepanel` namespace. Their values will be pulled when a new template is generated as outlined in #148
