### ISSUE TITLE
Move S3 specific config in artifactRepository under `s3` field:

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#158]
```
artifactRepository:
  s3:
    # S3 access key
    accessKey: <access-key>
    # Name of bucket, example: my-bucket
    bucket: mlpipeline.onepanel.io
    # Endpoint for S3 compatible storage
    # Supported provider endpoints:
    #   AWS: s3.amazonaws.com
    #   GCS: storage.googleapis.com
    #   Minio: my-minio-endpoint.default:9000
    endpoint: s3.amazonaws.com
    # Change to true if endpoint does NOT support HTTPS
    insecure: false
    # Bucket region
    region: us-west-2
    # S3 secret key
    secretKey: <secret-key>
```

Namespace [ConfigMap](https://github.com/onepanelio/manifests/blob/master/common/onepanel/base/configmap-onepanel-defaultnamespace.yaml) and [Secret](https://github.com/onepanelio/manifests/blob/master/common/onepanel/base/secret-onepanel-defaultnamespace.yaml) need to be updated.  

Update [`const`](https://github.com/onepanelio/core/blob/master/pkg/client.go#L17-L22) **values** only.

**Comment by aleksandrmelnikov** [comment]
@rushtehrani Do you want me to change the key values inside config map too?
Example:
```
  artifactRepositoryInsecure: $(artifactRepositoryS3Insecure)
```
Change to:
```
  artifactRepositoryS3Insecure: $(artifactRepositoryS3Insecure)
```

**Comment by rushtehrani** [comment]
Yes, we want to support other non-S3 compatible object storage. Eventually we'll probably store these as a multi line string in the ConfigMap. Not sure if that's a change we want to make now and parse the string accordingly or do this in a subsequent release when we add other object storage type.

**Comment by aleksandrmelnikov** [comment]
What are you envisioning the multi-line would look like?

**Comment by rushtehrani** [comment]
> What are you envisioning the multi-line would look like?

Very much similar to what Argo has [here](https://github.com/argoproj/argo/blob/master/docs/configure-artifact-repository.md#s3-compatible-artifact-repository-bucket-such-as-aws-gcs-and-minio) and [here](https://github.com/argoproj/argo/blob/master/docs/configure-artifact-repository.md#google-cloud-storage-gcs).

In fact, they now support native GCS too. We can integrate that in a subsequent release, but making the `param.yaml` change right now makes sense so we don't have to write a bunch of code for backwards compatibility.

```
artifactRepository: |
   s3:
    bucket: mlpipeline.onepanel.io
    endpoint: s3.amazonaws.com
    insecure: "false"
    region: us-west-2
    accessKeySecret:
       name: onepanel
       key: artifactRepositoryAccessKey
    secretKeySecret: 
       name: onepanel
       key: artifactRepositorySecretKey
```
