### ISSUE TITLE
Inject S3 system config info for `inputs`

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#207]
When user defines the following:
```
inputs:
      artifacts:
        - name: data
          path: /mnt/data/datasets/
          s3:
            key: '{{workflow.parameters.dataset-path}}'
```

Automatically inject the remaining fields:
```
            accessKeySecret:
              key: artifactRepositoryS3AccessKey
              name: onepanel
            bucket: <bucket-from-system-config>
            endpoint: s3.amazonaws.com
            insecure: <value-from-system-config>
            secretKeySecret:
              key: artifactRepositoryS3SecretKey
              name: onepanel
```

This is a workaround until [this issue](https://github.com/argoproj/argo/pull/3030) is addressed.
