### ISSUE TITLE
Native support for GCS artifact repository

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#331]
Support [GCS object storage](https://github.com/argoproj/argo/blob/master/docs/configure-artifact-repository.md)

Docs and params.yaml comments need to also be updated accordingly.

**Comment by aleksandrmelnikov** [comment]
When testing the in-progress code.
- Need to pull down manifests repo, core, and cli.
- All use the same `feat/core.331-support.gcs.artifact[..]` branch

The CLI repository relies on a library from core.
So, make sure to pull down the core branch first.

Then, in CLI repo, in `go.mod`, add this line
```
module github.com/onepanelio/cli

go 1.13

# This one, replace it with your relevant path.
replace github.com/onepanelio/core v0.11.0 => /home/aleksandr/Code/onepanelio/core
```

**Comment by aleksandrmelnikov** [comment]
### Volume Binding Issues
Ensure your kubectl client and kubectl server versions match: 
`kubectl version --short=true`, if not, change your client to match your server.
Check that the storageClass of the PVC and PV match: 
`kubectl get pv` and `kubectl get pvc -n <namespace>`

Edit the storage-provisioner image from 1.8.1, or similiar, to “latest”
![Pasted image](https://user-images.githubusercontent.com/10407733/87360621-66592e00-c51f-11ea-8440-407f8e948302.png)

Then add the following…
`kubectl edit clusterrole -n kube-system system:persistent-volume-provisioner`
And add new permissions there
```yaml
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
```

**Comment by aleksandrmelnikov** [comment]
To test inline artifact setting with GCS / S3, this is an example for GCS.
```yaml
entrypoint: main
arguments:
  parameters:
    - name: source
      value: 'https://github.com/onepanelio/tensorflow-examples.git'
    - name: command
      value: python mnist/main.py --epochs=5
volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
  - metadata:
      name: output
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
templates:
  - name: main
    dag:
      tasks:
        - name: train-model
          template: pytorch
        - name: test
          template: test
          dependencies:
            - train-model
  - name: pytorch
    inputs:
      artifacts:
        - name: src
          path: /mnt/src
          git:
            repo: '{{workflow.parameters.source}}'
    outputs:
      artifacts:
        - name: model
          path: /mnt/output
          optional: true
          archive:
            none: {}
    container:
      image: 'tensorflow/tensorflow:latest'
      command:
        - sh
        - '-c'
      args:
        - '{{workflow.parameters.command}}'
      workingDir: /mnt/src
      volumeMounts:
        - name: data
          mountPath: /mnt/data
        - name: output
          mountPath: /mnt/output
  - name: test
    container:
      image: alpine
      command:
        - sh
        - '-c'
      args:
        - echo "gcstest" >> /tmp/alexwashere.log
    outputs:
      artifacts:
        - name: test
          path: /tmp/
          gcs:
            bucket: core311two
            key: /alex/
            serviceAccountKeySecret:
              name: onepanel
              key: serviceAccountKey
  - name: slack-notify-success
    container:
      image: technosophos/slack-notify
      command:
        - sh
        - '-c'
      args:
        - 'SLACK_USERNAME=Worker SLACK_TITLE="{{workflow.name}} {{inputs.parameters.status}}" SLACK_ICON=https://www.gravatar.com/avatar/5c4478592fe00878f62f0027be59c1bd SLACK_MESSAGE=$(cat /tmp/metrics.json)} ./slack-notify'
    inputs:
      parameters:
        - name: status
      artifacts:
        - name: metrics
          path: /tmp/metrics.json
          optional: true
```
