### ISSUE TITLE
Add `resource.requests` and `resource.limits` to nodePool

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#392]
Extend `options` field in `nodePool` to take resource requests and limits:

```yaml
nodePool:
label: beta.kubernetes.io/instance-type
options:
- name: 'CPU: 4, RAM: 16GB'
  value: Standard_D4s_v3
  resources:
    limits:
      memory: '16Gi'
      cpu: '4'
      nvidia/gpu: 0
```
