### ISSUE TITLE
Posix shared memory across containers in pods

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#4]
Every `Pod` needs this added to support [Posix Shared Memory across containers in pods](https://github.com/kubernetes/kubernetes/issues/28272)

```
volumeMounts:
  - mountPath: /dev/shm
    name: dshm
```
```
volumes:
 - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: "256Mi"
```

Note that `sizeLimit` is optional and depends on: https://github.com/kubernetes/kubernetes/pull/63641
