### ISSUE TITLE
Spec error not caught during WorkflowTemplate validation

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#442]
This was thrown during runtime and also is not displayed in the UI:

```
Status:
  Conditions:
    Status:     True
    Type:       Completed
  Finished At:  2020-07-29T18:34:32Z
  Message:      invalid spec: templates.main.tasks[5].name 'sys-send-status' is not unique
  Phase:        Failed
  Started At:   2020-07-29T18:34:32Z
Events:         <none>
```

**Comment by rushtehrani** [comment]
Actually, this looks like an issue with auto-injected tasks so they won't be caught during WorkflowValidation. This is the WorkfowTemplate that causes this issue:

```yaml
entrypoint: main
templates:
  - name: main
    dag:
      tasks:
      - name: train-pytorch-model
        template: pytorch
      - name: train-tensorflow-model
        template: tensorflow
      - name: notify-in-slack-tensorflow
        dependencies: [train-tensorflow-model]
        template: slack-notify-success
        arguments:
          parameters:
          - name: status
            value: "{{tasks.train-tensorflow-model.status}}"
          artifacts:
          - name: metrics
            from: "{{tasks.train-tensorflow-model.outputs.artifacts.sys-metrics}}"
      - name: notify-in-slack-pytorch
        dependencies: [train-pytorch-model]
        template: slack-notify-success
        arguments:
          parameters:
          - name: status
            value: "{{tasks.train-pytorch-model.status}}"
          artifacts:
          - name: metrics
            from: "{{tasks.train-pytorch-model.outputs.artifacts.sys-metrics}}"
  - name: tensorflow
    inputs:
      artifacts:
      - name: src
        path: /mnt/src
        git:
          repo: "https://github.com/onepanelio/tensorflow-examples.git"
    outputs:
      artifacts:
      - name: model
        path: /mnt/output
        optional: true
        archive:
          none: {}
    container:
      image: tensorflow/tensorflow:latest
      command: [sh,-c]
      args: ["python mnist/main.py --epochs=1"]
      workingDir: /mnt/src
  - name: pytorch
    inputs:
      artifacts:
      - name: src
        path: /mnt/src
        git:
          repo: "https://github.com/onepanelio/pytorch-examples.git"
    outputs:
      artifacts:
      - name: model
        path: /mnt/output
        optional: true
        archive:
          none: {}
    container:
      image: pytorch/pytorch:latest
      command: [sh,-c]
      args: ["python mnist/main.py --epochs=1"]
      workingDir: /mnt/src
  - name: slack-notify-success
    container:
      image: technosophos/slack-notify
      command: [sh,-c]
      args: ['SLACK_USERNAME=Worker SLACK_TITLE="{{workflow.name}} {{inputs.parameters.status}}" SLACK_ICON=https://www.gravatar.com/avatar/5c4478592fe00878f62f0027be59c1bd SLACK_MESSAGE=$(cat /tmp/metrics.json)} ./slack-notify']
    inputs:
      parameters:
      - name: status
      artifacts:
      - name: metrics
        path: /tmp/metrics.json
        optional: true
```
