### ISSUE TITLE
Update parameters to have a meta field

### ISSUE THREAD

**Issue by Vafilor** [onepanelio/core#454]
```
- name: selection
  value: ...
  metaData:
    visibility: internal
    type: input.select
    options:
    - name: ...
      value: ...
```
