### ISSUE TITLE
CVAT UI issues

### ISSUE THREAD

**Issue by Vafilor** [onepanelio/core#606]
- [x] Not enough space is not shown in UI in shared files 
- [x] Expanding any element for files always pulls down the data (network request is made) it should be caching that data

**Comment by savan77** [comment]
can you share a sample filesyncer api/status response when this happens?

**Comment by Vafilor** [comment]
@rushtehrani cc @savan77  Can you give test this one when you get a chance?

Workspace Template
```yaml
# Workspace arguments
arguments:
  parameters:
  - name: sync-directory
    displayName: Directory to sync raw input and training output
    value: workflow-data
    hint: Location to sync raw input, models and checkpoints from default object storage. Note that this will be relative to the current namespace.
containers:
- name: cvat-db
  image: postgres:10-alpine
  env:
  - name: POSTGRES_USER
    value: root
  - name: POSTGRES_DB
    value: cvat
  - name: POSTGRES_HOST_AUTH_METHOD
    value: trust
  - name: PGDATA
    value: /var/lib/psql/data
  ports:
  - containerPort: 5432
    name: tcp
  volumeMounts:
  - name: db
    mountPath: /var/lib/psql
- name: cvat-redis
  image: redis:4.0-alpine
  ports:
  - containerPort: 6379
    name: tcp
- name: cvat
  image: onepanel/cvat:0.12.0_cvat.1.0.0
  env:
  - name: DJANGO_MODWSGI_EXTRA_ARGS
    value: ""
  - name: ALLOWED_HOSTS
    value: '*'
  - name: CVAT_REDIS_HOST
    value: localhost
  - name: CVAT_POSTGRES_HOST
    value: localhost
  - name: CVAT_SHARE_URL
    value: /home/django/data
  - name: ONEPANEL_SYNC_DIRECTORY
    value: '{{workspace.parameters.sync-directory}}'
  - name: NVIDIA_VISIBLE_DEVICES
    value: all
  - name: NVIDIA_DRIVER_CAPABILITIES
    value: compute,utility
  - name: NVIDIA_REQUIRE_CUDA
    value: "cuda>=10.0 brand=tesla,driver>=384,driver<385 brand=tesla,driver>=410,driver<411"
  ports:
  - containerPort: 8080
    name: http
  volumeMounts:
  - name: data
    mountPath: /home/django/data
  - name: keys
    mountPath: /home/django/keys
  - name: logs
    mountPath: /home/django/logs
  - name: models
    mountPath: /home/django/models
  - name: share
    mountPath: /home/django/share
  - name: sys-namespace-config
    mountPath: /etc/onepanel
    readOnly: true
- name: cvat-ui
  image: onepanel/cvat-ui:staging-fs-test-oom-6
  ports:
  - containerPort: 80
    name: http
# You can add multiple FileSyncer sidecar containers if needed
- name: filesyncer
  image: onepanel/filesyncer:s3-api.update
  imagePullPolicy: Always
  command: ["/bin/sh", "-c"]
  args: ["until curl --head localhost:15000 ; do echo Waiting for Sidecar; sleep 3 ; done ; echo Sidecar available; sleep 30; filesyncer download -server-prefix=/sys/filesyncer"]
  env:
  - name: FS_PATH
    value: /mnt/share
  - name: FS_PREFIX
    value: '{{workflow.namespace}}/{{workspace.parameters.sync-directory}}'
  volumeMounts:
  - name: share
    mountPath: /mnt/share
  - name: sys-namespace-config
    mountPath: /etc/onepanel
    readOnly: true
ports:
- name: cvat-ui
  port: 80
  protocol: TCP
  targetPort: 80
- name: cvat
  port: 8080
  protocol: TCP
  targetPort: 8080
- name: fs
  port: 8888
  protocol: TCP
  targetPort: 8888
routes:
- match:
  - uri:
      prefix: /sys/filesyncer
  route:
  - destination:
      port:
        number: 8888
- match:
  - uri:
      regex: /api/.*|/git/.*|/tensorflow/.*|/onepanelio/.*|/tracking/.*|/auto_annotation/.*|/analytics/.*|/static/.*|/admin/.*|/documentation/.*|/dextr/.*|/reid/.*
  - queryParams:
      id:
        regex: \d+.*
  route:
  - destination:
      port:
        number: 8080
  timeout: 600s
- match:
  - uri:
      prefix: /
  route:
  - destination:
      port:
        number: 80
  timeout: 600s
```
