### ISSUE TITLE
Workflows failure with more than one root element.

### ISSUE THREAD

**Issue by Vafilor** [onepanelio/core#667]
The following template currently fails.

```yaml
entrypoint: diamond
templates:
- name: echo
  inputs:
    parameters:
    - name: message
  container:
    image: alpine:3.7
    command: [echo, "{{inputs.parameters.message}}"]
- name: diamond
  dag:
    tasks:
    - name: A
      template: echo
      arguments:
        parameters: [{name: message, value: A}]
    - name: B
      template: echo
      arguments:
        parameters: [{name: message, value: B}]
```
