### ISSUE TITLE
Azure MinIO Gateway

### ISSUE THREAD

**Issue by inohmonton99** [onepanelio/core#795]
### In-cluster Azure MinIO gateway deployment

Proposed params.yaml structure:
```yaml
artifactRepository:
  abs:
    container: <container-name>
    storageAccountName: <storage-account-name>
    storageAccountKey: <storage-account-key>
```

Sample resources that need to be included and generated in manifests:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: minio-gateway
  namespace: onepanel
spec:
  selector:
    app: minio-gateway
  ports:
    - port: 9000
      targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-gateway
  namespace: onepanel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-gateway
  template:
    metadata:
      labels:
        app: minio-gateway
    spec:
      containers:
        - name: minio-gateway
          image: minio/minio
          args:
            - gateway
            - azure
          env:
            - name: MINIO_ACCESS_KEY
              value: '<azure-storage-account-name>'
            - name: MINIO_SECRET_KEY
              value: '<azure-storage-account-key>'
          ports:
            - containerPort: 9000
```
