### ISSUE TITLE
Allow variable references in Workflow and Workspace parameters

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#828]
Example:

```yaml
arguments:
  parameters:
  - name: artifacts-location
    value: artifacts/{{workflow.namespace}}/
```

Only [global variables](https://argoproj.github.io/argo/variables/#global) should be supported.
