### ISSUE TITLE
GCS MinIO Gateway

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#836]
### In-cluster GCS MinIO gateway deployment

Proposed params.yaml structure:
```yaml
artifactRepository:
  gcs:
    bucket: <bucket-name>
    projectId: <project-id>
    region: us-west1
    keyFormat: artifacts/{{workflow.namespace}}/{{workflow.name}}/{{pod.name}}
    serviceAccountKey: |
      {
        "type": "service_account",
        "project_id": "my-project-id",
        "private_key_id": "private_key_id",
        "private_key": "private_key",
        "client_email": "client_email",
        "client_id": "client_id",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_x509_cert_url": "cert_url"
      }
```

Sample resources that need to be included and generated in manifests:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: minio-gateway
  namespace: onepanel
spec:
  selector:
    app: minio-gateway
  ports:
    - port: 9000
      targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-gateway
  namespace: onepanel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-gateway
  template:
    metadata:
      labels:
        app: minio-gateway
    spec:
      containers:
        - name: minio-gateway
          image: minio/minio
          volumeMounts:
            - name: gcs
              mountPath: /etc/gcs
          args:
            - gateway
            - gcs
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: onepanel
                  key: artifactRepositoryS3AccessKey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: onepanel
                  key: artifactRepositoryS3SecretKey
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/gcs/credentials.json
      volumeMounts:
      - name: gcs-credentials
        mountPath: "/etc/gcs"
        readOnly: true
volumes:
  - name: gcs-credentials
    projected:
      sources:
        - secret:
            # This secret should have a key `credentials.json`
             name: artifactRepositoryGCSCredentials
```
